function grouped_image_generator_cached = get_grouped_image_generator2_caching(folder, ...
                                                                        glob_matchers,...
                                                                        grouper,...
                                                                        use_cache_file,...
                                                                        ban_files,...
                                                                        ban_list,...
                                                                        img_mods_dict,...
                                                                        characteristic_string,...
                                                                        save_folder)

grouped_image_generator = get_grouped_image_generator2(folder, ...
                                                       glob_matchers, ...
                                                       grouper, ...
                                                       use_cache_file, ...
                                                       ban_files, ...
                                                       ban_list);

if(kv_haskey('image_modifiers',img_mods_dict))
    image_modifiers=kv_haskey('image_modifiers',img_mods_dict);
    grouped_image_generator = grouped_image_generator.set_image_modifiers(image_modifiers);
end

if(kv_haskey('structured_image_modifiers',img_mods_dict))
    structured_image_modifiers=kv_haskey('structured_image_modifiers',img_mods_dict);
    grouped_image_generator = grouped_image_generator.set_structured_image_modifiers(structured_image_modifiers);
end

if(~exist('save_folder','var'))
    save_folder = folder;
end

cached_grouped_image_generator_path = path_join(save_folder,[characteristic_string '.mat']);

grouped_image_generator_cached=GroupedImageGenerator2Cached(cached_grouped_image_generator_path,grouped_image_generator);



